@startuml
actor       用户          as USER
entity      门店收银台       as CHECKOUT
entity      DolphinPay支付系统       as PAY

activate CHECKOUT
CHECKOUT -> CHECKOUT: 1. 预下单，生成二维码
CHECKOUT --> USER: 2. 展示二维码给用户
deactivate CHECKOUT
activate USER
USER -> PAY: 3.扫描二维码，确认支付方式
deactivate USER
activate PAY
PAY --> USER: 返回用户选择支付方式的页面进行支付
deactivate PAY
activate USER
USER -> PAY: 4.用户确认支付，输入密码
deactivate USER
alt 用户正确输入密码
    USER -> PAY: 4.用户确认支付，输入密码
    activate USER
    activate PAY
    PAY -> PAY: 5.执行支付流程
    PAY --> CHECKOUT: 5.1 返回支付结果
    PAY --> USER: 5.2 返回支付结果，发送支付订单详情
    deactivate PAY
    deactivate USER
else 用户密码错误
    USER -> PAY: 4 输入密码
    activate USER
    activate PAY
    PAY -> PAY: 5.执行支付流程
    PAY --> CHECKOUT: 5.1 密码错误，等待重试
    PAY --> USER: 5.2 展示密码错误，需要重新输入密码
    deactivate PAY
    deactivate USER
else 用户取消操作
    USER -> PAY: 4 取消输入密码
    activate PAY
    PAY -> PAY: 5.订单进入待支付状态
    PAY --> CHECKOUT: 5.1 顾客取消支付，等待顾客重新付款
    deactivate PAY
end
@enduml