@startuml
actor       用户          as USER
entity      DolphinPay客户端    as APP
actor       收银员         as CASHIER
entity      扫描终端       as SCAN
entity      门店收银台       as CHECKOUT
entity      DolphinPay支付系统       as PAY

activate USER
USER -> APP : 2.选择卡包中的支付方式
activate CHECKOUT
CASHIER -> CHECKOUT:1.生成支付订单（order_id）
CHECKOUT --> USER: 展示订单信息
deactivate CHECKOUT
APP -> SCAN: 3.用户展示的付款授权码
SCAN -> CHECKOUT: 4.上传收到的用户付款码信息
CHECKOUT -> PAY: 5.请求支付
activate PAY
PAY->PAY: 6.执行支付逻辑
PAY --> USER: 6.1 等待用户输入密码
deactivate PAY
deactivate USER
alt 用户正确输入密码
    USER -> PAY: 6.2 输入密码
    activate PAY
    PAY --> CHECKOUT: 7.返回支付结果
    PAY --> APP: 7.1 返回支付结果，发送支付订单详情
    CASHIER ->CASHIER: 8. 收银员完成支付流程，发货打印小票
    deactivate PAY
else 用户密码错误
    USER -> PAY: 6.2 输入密码
    activate PAY
    PAY --> CHECKOUT: 7.密码错误，等待重试
    PAY --> APP: 7.1 展示密码错误，需要重新输入密码
    deactivate PAY
else 用户取消操作
    USER -> PAY: 6.2 取消输入密码
    activate PAY
    PAY -> PAY: 7.订单进入待支付状态
    PAY --> CHECKOUT: 7.1 顾客取消支付，等待顾客重新付款
    deactivate PAY
end
@enduml