@startuml
actor       用户          as USER
actor       收银员         as CASHIER
entity      门店收银台       as CHECKOUT
entity      DolphinPay支付系统       as PAY

group 整单退款
    CASHIER -> CHECKOUT: 1.发起退款请求
    CHECKOUT -> PAY: 2.整单退款请求
    PAY -> PAY: 3. 退款流程
    PAY --> CHECKOUT: 4. 返回退款结果，修改订单状态为已退款
    PAY --> USER: 4.1 发送退款成功消息，原路退回资金
end
group 部分退款
    CASHIER -> CHECKOUT: 1.发起退款请求
    CHECKOUT -> PAY: 2.部分退款请求
    PAY -> PAY: 3. 退款流程
    PAY --> CHECKOUT: 4. 返回退款结果，修改订单状态为部分退款
    PAY --> USER: 4.1 发送退款成功消息，原路退回资金
end
@enduml