@startuml
actor       用户          as USER
entity      熊猫支付客户端    as APP
actor       收银员         as CASHIER
entity      扫描终端       as SCAN
entity      门店收银台       as CHECKOUT
entity      熊猫支付系统       as PAY

USER -> APP : 2.选择卡包中的支付方式
CASHIER -> CHECKOUT:1.生成支付订单（order_id）
CHECKOUT --> USER: 展示订单信息
APP -> SCAN: 3.用户展示的付款授权码
SCAN -> CHECKOUT: 4.上传收到的用户付款码信息
CHECKOUT -> PAY: 5.请求支付
PAY->PAY: 6.执行支付逻辑
PAY --> CHECKOUT: 7.返回支付结果
PAY --> APP: 7.1 返回支付结果，发送支付订单详情
CASHIER ->CASHIER: 8. 收银员完成支付流程，发货打印小票
@enduml